package-lock.json

[setting] package-lock.json 수정

---

src/components/Button/Button.tsx
src/components/Button/ButtonGoogle.tsx
src/components/Button/ButtonKakao.tsx
src/components/Input/Input.module.scss
src/components/Input/Input.tsx

#23 
✨ 구현 기능 명세
[Input(with Label) 컴포넌트 props 작성 요령]
- maxWidthValue : width 값 설정입니다. 반응형 생각해서 운기님 코드를 그대로 차용했습니다.
- heightValue : height 값 설정입니다.
- labelText : Label이 필요한 경우에만 작성합니다. 작성 시 `htmlFor` 도 같이 작성되게 끔 코드 짰습니다.
- placeHolder : placeholder 값이 필요한 경우에만 작성합니다.
🎁 PR Point
- Pigma 시안의 디자인이 모두 통일 되어 있지 않아 제 임의대로 css 를 수정했습니다.
- `Button` 컴포넌트의 export 부분 코드 수정해서 같이 PR 드립니다.
😭 어려웠던 점
- 아직도 type 지정을 할 줄 몰라서 빨간 줄 무시하고 작업 진행 했습니다.

[feat] Input(with Label) 컴포넌트 구현

---

src/components/InputSelector/InputSelector.module.scss
src/components/InputSelector/InputSelector.tsx

#26 
✨ 구현 기능 명세
지역을 선택하세요 select 클릭 시 값 가져오기
🎁 PR Point
.
😭 어려웠던 점
useState 사용 하여 리-렌더링 문제가 생김,,해결을 아직 못했습니다.

[feat] InputSelector UI구현 완성 - useState로 구현

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/pages/Chat/Chat.module.scss

✨ 구현 기능 명세
- Card UI Component 구현
🎁 PR Point
- .
😭 어려웠던 점
- .

[feat] Card UI Component 구현

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/pages/MainPage/MainPage.module.scss

#42 
✨ 구현 기능 명세
[chore] MainPage mainPageCard 모바일 디바이스 CSS 리팩토링
[chore] Card UI 반응형 리팩토링,
Props 리팩토링
🎁 PR Point
😭 어려웠던 점
그리드 스타일링 가운데정렬 이슈가 있었지만 잘 해결했습니다.!

[style] MainPage Card 반응형 구현

---

src/components/Input/SearchForm.tsx
src/components/Input/SearchFrom.module.scss
src/components/InputSelector/InputSelector.tsx
src/components/Modal/Modal.module.scss
src/components/Modal/ModalTotal.tsx
src/utils/MapContainer.module.scss
src/utils/MapContainer.tsx

#52 
✨ 구현 기능 명세
[style] MapContainer CSS 파일 추가
[feat] 클릭시 Marker 표시 추가 (경도,위도 메시지 콘솔 출력 )
[chore] Modal 리팩토링
className 추가
반응형 스타일 코드 추가
modalContent max-width 값 변경
[chore] SearchForm props 리팩토링
[chore] InputSelector component props 수정
🎁 PR Point
아직 PR타이밍을 잘 몰라서,,,점점 수정해 나가겠습니다.!
😭 어려웠던 점
반응형 스타일을 아직 완벽히 구사하지 못했습니다. 또한 클린코드를 하기위해,,,좀더 생각이 필요합니다.

메인페이지 - Map API 클릭시 Marker 표시하기

---

src/components/ChatDialog/Navbar/Navbar.module.scss
src/components/ChatDialog/Sidebar/Sidebar.module.scss
src/pages/NotFound/NotFound.module.scss
src/pages/NotFound/NotFound.tsx

#61 
✨ 구현 기능 명세
-  NotFound Page UI 구현
🎁 PR Point
- .
😭 어려웠던 점
- .

 [style] NotFound Page UI 구현 

---

public/assets/banner_1.svg
public/assets/banner_2.svg
public/assets/banner_3.svg
src/components/Banner/Banner.module.scss
src/components/Banner/Banner.tsx
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/Card/Meeting.tsx
src/components/Input/Input.tsx
src/components/Input/SearchForm.tsx
src/components/Input/SearchFrom.module.scss
src/components/InputSelector/InputSelector.module.scss
src/components/InputSelector/InputSelector.tsx
src/components/Modal/Form.tsx
src/components/Modal/ModalTotal.tsx
src/components/Modal/ReadMeetings.tsx
src/components/Modal/ShowMeetings.tsx
src/firebase/storage/index.ts
src/pages/MainPage/MainPage.tsx

#68 #69 
✨ 구현 기능 명세
- [feat] 모임카드 클릭시 -> 팝업창 open, close 기능 구현 -> 데이터 전송은 진행중인 상태
- [style] MainPage 광고 배너 반응형 크기 구현 완료
🎁 PR Point
- firebase 파일 주소 항상 유념해주세요. @ 앞에 붙여야 합니다!
😭 어려웠던 점
- page가 아닌 컴포넌트(모달)을 열고 닫으려니까 간단하지 않았다.
- useState를 이용하여 조건문을 걸어주었다.

[feat] 모임카드 Read 팝업창 open, close 기능 구현

---

src/components/Button/ButtonGoogle.tsx
src/components/Button/ButtonKakao.tsx
src/components/Input/Input.tsx

#3 #23 
✨ 구현 기능 명세
- ButtonGoogle, ButtonKakao 에 `widthValue`, `maxWidthValue`, `heightValue` prop 추가했습니다.
- Input 에 `disabled` prop 추가했습니다.
🎁 PR Point
😭 어려웠던 점

[chore] 컴포넌트 수정 (ButtonGoogle, ButtonKakao, Input)

---

src/components/Button/ButtonGoogle.tsx
src/components/ChatDialog/Navbar/Navbar.tsx
src/components/SignIn/SignIn.tsx
src/components/SignUP/SignUp.module.scss
src/components/SignUP/SignUp.tsx
src/context/AuthContext.tsx
src/main.tsx
src/pages/Chat/Chat.module.scss

#92 
✨ 구현 기능 명세
- 로그인 & 회원가입 기능 구현
- auth context로 관리  
🎁 PR Point
.
😭 어려웠던 점
- 파이어베이스 연결하는 과정에서  오류가 발생해 어려웠다..

[feat] 로그인 & 회원가입 기능 구현

---

index.html
src/components/InputSelector/InputSelector.tsx
src/components/Modal/ModalTotal.tsx
src/utils/MapContainer.tsx

#97 
✨ 구현 기능 명세
map - 주소 - 좌표 변경 코드 추가
inputSelector 구 주소 추가
🎁 PR Point
😭 어려웠던 점
주소를 받아오는걸 실패하여,,다른 방법을 찾아보겠습니다.!

[style] map api 수정 및 inputSelector 주소 추가

---

src/components/Footer/Footer.module.scss
src/components/Footer/Footer.tsx

#77 
✨ 구현 기능 명세
[style] logoText 추가 및 font-size 단위 수정
🎁 PR Point
😭 어려웠던 점

[style] logoText 추가 및 font-size 단위 수정

---

package-lock.json
package.json
src/components/InputSelector/InputSelector.tsx
src/components/Modal/Modal.module.scss
src/components/Modal/ModalTotal.tsx
src/components/Modal/ReadMeetings.tsx
src/components/Modal/ShowMeetings.tsx

#102 
✨ 구현 기능 명세
card클릭시 localStorage uniqueID에 documentID값이 저장됨
firestore -> documentID === localStorage uniqueID 일 경우, 해당 데이터 모달창에 뿌려주기
🎁 PR Point
.
😭 어려웠던 점
firebase에서 document ID를 가져오는 코드를 작성하는 것에 어려움이 있었다.
https://github.com/yamoo9/likelion-FEQA/issues/183 참고하여 작성하였다.
해결 핵심 코드는 아래와 같다.
`const usersCollectionRef = query(
collection(db, 'makeMeetings'),
where(
firebase.firestore.FieldPath.documentId(),
'==',
localStorage.getItem('Unique ID')
)
);`

[feat] Card firestore로부터 Read 후, 모달창에 정보 띄우기

---

index.html
src/components/ChatDialog/Chatting/Chatting.tsx
src/components/ChatDialog/Message/Message.module.scss
src/components/ChatDialog/Message/Message.tsx
src/components/ChatDialog/Messages/Messages.tsx
src/components/ChatDialog/Search/Search.tsx
src/components/ChatDialog/SendMessage/SendMessage.tsx
src/components/SignIn/SignIn.tsx
src/components/SignUP/SignUp.tsx
src/pages/Home/Home.tsx
src/pages/Recommend/Recommend.tsx

#109 
✨ 구현 기능 명세
- [feat] 채팅 창에 메세지입력시 메세지 생성 
- 파이어베이스 연결
🎁 PR Point
- .
😭 어려웠던 점
- 채팅 데이터베이스 구성하고 연결하는 과정이 어려웠다..

[feat] 채팅 창에 메세지입력시 메세지 생성

---

src/components/ProfileImage/ProfileImage.tsx

#112 #113 
✨ 구현 기능 명세
- 회원가입 된 user 마다 uid기반으로 이미지를 업로드하고 다운로드하는 기능
🎁 PR Point
😭 어려웠던 점
- 페이지를 새로고침 하자마자 uid가 undefined가 되어서 저장된 이미지를 못 불러오는 이슈..

[feat] ProfileImage 이미지 불러오기 구현

---

src/App.tsx
src/components/ChatDialog/Messages/Messages.tsx
src/components/ChatDialog/SendMessage/SendMessage.module.scss
src/components/ChatDialog/SendMessage/SendMessage.tsx
src/context/AuthContext.tsx
src/pages/Home/Home.tsx
src/pages/Layout/Layout.tsx

#111 #114 
✨ 구현 기능 명세
- 라우터 연결 리펙토링
- 채팅 입력시 스크롤바 최신순으로 조정
🎁 PR Point
-.
😭 어려웠던 점
- 스크롤바 조정하는 로직 구현 과정이 어려웠다.

[feat] 채팅 입력시 스크롤바 최신순으로 조정

---

src/components/Modal/ShowCard.tsx
src/utils/MapContainer.tsx

✨ 구현 기능 명세
#106 
지도 랜더링이 되었다안되었다하여 코드 일부 수정해서 업데이트 해줌.
🎁 PR Point
지도 랜더링이 해당 위치별로 잘되는지 체크. 
😭 어려웠던 점
`setMapLocation([coords['Ma'], coords['La']]);` 이코드가 핵심이었습니다..

[fix] 지도 마커 미이동시 에러났던거 해결

---

src/components/ChatDialog/Navbar/Navbar.tsx
src/components/Modal/ReadMeetings.tsx
src/context/AuthContext.tsx

✨ 구현 기능 명세
- fireStore 이미지 주소값 불러오기
🎁 PR Point
.
😭 어려웠던 점
.

[feat] fireStore에서 채팅 이미지 데이터 받아오기

---

src/components/ChatDialog/Navbar/Navbar.tsx

#49 
✨ 구현 기능 명세
- 마이페이지 프로필 이미지 다운받듯이 똑같이 구현했습니다.
🎁 PR Point
😭 어려웠던 점

[feat] nav 프로필 이미지 불러오기 구현

---

src/components/Input/Input.tsx
src/components/ProfileImage/ProfileImage.tsx
src/components/SignUP/SignUp.tsx
src/pages/MyPage/MyPage.module.scss
src/pages/MyPage/MyPage.tsx

#23 #80 #92 #126 #127 #128
✨ 구현 기능 명세
- 작업하는 과정에서 여러 파일을 수정하였습니다.
- 핵심적인 기능은 제목과 같이 **마이페이지 user 데이터 input에 불러오기 / 로그아웃 기능 구현** 입니다.
🎁 PR Point
- 커밋을 한꺼번에 넘기다 보니 파일 확인을 잘 해주셔야 합니다.
😭 어려웠던 점
- 페이지 리렌더링 문제를 해결하지 못했습니다.
- 올바르게 작성한 코드인지는 모르겠습니다. 일단은 기능 구현에는 성공했습니다.

[feat] 마이페이지 user 데이터 input에 불러오기 / 로그아웃 기능 구현

---

index.html
src/components/Banner/Banner.module.scss
src/components/Banner/HomeBanner.tsx
src/components/Button/ButtonGoogle.tsx
src/components/Button/ButtonKakao.tsx
src/components/LogoText/LogoText.module.scss
src/components/Modal/Modal.module.scss
src/components/Modal/Modal.tsx
src/components/SignIn/SignIn.module.scss
src/components/SignIn/SignIn.tsx
src/components/SignUP/SignUp.module.scss
src/components/SignUP/SignUp.tsx
src/pages/Home/Home.module.scss
src/pages/Home/Home.tsx
src/states/signState.ts

#138 
✨ 구현 기능 명세
Home (첫 화면 페이지) 회원가입, 로그인 클릭시 각각 맞는 UI 모달창 띄우기 했습니다.
아직 접근성은 고려하지 못하여 이제 수정하려고 합니다.
🎁 PR Point
수정사항이 너무 많아,,,한번에 많이 올립니다.
😭 어려웠던 점
처음에 모달창에 넣기 성공하였지만,,이벤트 거는 법을 몰라 시간이 걸렸습니다.

[feat] 홈 (첫 화면 페이지) - 로그인, 회원가입 버튼 클릭시 모달창 띄우기

---

public/assets/defaultAvatars.svg
src/components/ChatDialog/Chatting/Chatting.module.scss
src/components/ChatDialog/Chatting/Chatting.tsx
src/components/ChatDialog/Message/Message.module.scss
src/components/ChatDialog/Message/Message.tsx
src/components/ChatDialog/Navbar/Navbar.module.scss
src/components/ChatDialog/Navbar/Navbar.tsx
src/components/ChatDialog/Search/Search.tsx
src/components/ChatDialog/SendMessage/SendMessage.module.scss
src/components/ChatDialog/SendMessage/SendMessage.tsx
src/components/ChatDialog/Sidebar/Sidebar.module.scss
src/components/ChatDialog/Sidebar/Sidebar.tsx
src/components/SignIn/SignIn.tsx
src/pages/Chat/Chat.tsx
src/pages/MyPage/MyPage.tsx
src/pages/NotFound/NotFound.tsx
src/pages/Recommend/Recommend.tsx
src/states/authImgState.ts

#117 #135
✨ 구현 기능 명세
채팅 - 이미지 업로드 기능 구현
- 마이페이지에서 바뀐 이미지 프로필에 적용하기 
- image 값이 없을때 기본이미지로 적용되게 하기
🎁 PR Point
각 페이지에 usenavigation hook을 추가해 두었습니다!
😭 어려웠던 점
이미지를 메세지와 같이 띄우게 하는과정레서 어려움이있었다..

[feat] 채팅 - 이미지 업로드 기능 구현

---

src/components/ChatDialog/SendMessage/SendMessage.tsx
src/utils/validation.ts

#143 
✨ 구현 기능 명세
-  벨리데이션 검사 함수 구현
🎁 PR Point
- .
😭 어려웠던 점
- .

[feat] 벨리데이션 검사 함수

---

src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/components/Input/Input.tsx
src/components/Input/SearchForm.tsx
src/components/Input/SearchFrom.module.scss
src/components/InputSelector/InputSelector.tsx
src/components/Modal/ReadMeetings.tsx
src/components/Modal/lazyMinLoadTime.tsx
src/pages/MyPage/MyPage.tsx
src/utils/MapContainer.tsx

#146 
✨ 구현 기능 명세
모임만들기 카드 검색기능 구현   
-> selector로 address선택, input창에 제목 작성 후 검색(돋보기버튼) 클릭 or Enter 시 해당 카드만 랜더링되게 구현.
-> OR을 걸어주지 않아서 selector와 input 모두 일치해야 검색이 됨.
🎁 PR Point
검색 기능 잘 작동되는지 검토.
😭 어려웠던 점
fireStore에서 데이터 찾을 때 where 조건문에서 OR기능 쓰기 -> 미해결
fireStore에서 데이터 찾을 때 일부 제목만 입력하고 검색해도 나오게 하기 -> 미해결

[feat] 모임만들기 Card - search filter 기능 구현

---

src/components/Button/ButtonGoogle.tsx
src/components/Button/ButtonKakao.tsx
src/pages/Home/Home.tsx
src/pages/MyPage/MyPage.module.scss

#3 #31 #138 
✨ 구현 기능 명세
- 구글, 카카오 버튼 컴포넌트에 `회원가입` 기능 삭제했습니다. -> `Home.tsx` 의 코드 또한 수정 완료
- MyPage SCSS 리팩토링 했습니다.
🎁 PR Point
- 마이페이지 반응형 잘 작동되는지 확인 한 번 부탁드립니다!
😭 어려웠던 점
- 마이페이지 반응형 작업 중에 className을 많이 부여해서 SCSS 코드가 깨끗하게 만들지 못했습니다.

[chore] 구글, 카카오 버튼 & MyPage SCSS 리팩토링

---

src/components/ChatDialog/Navbar/Navbar.tsx
src/components/ProfileImage/ProfileImage.tsx

#152 
✨ 구현 기능 명세
- 조만간 변경 될 SignUp.tsx에 맞춰서 ProfileImage, Navbar 컴포넌트의 프로필 이미지를 defaultAvatar 통일했습니다. 
```typescript
```
🎁 PR Point
😭 어려웠던 점

[chore] 프로필 이미지 defaultAvatar로 통일

---

src/pages/MainPage/MainPage.tsx
src/pages/MyPage/MyPage.tsx

#141 #157 
✨ 구현 기능 명세
- `MyPage.tsx` 에 debounce 함수를 직접 제작한 코드를 넣어서 onChange 문제를 해결했습니다. (type 지정만 추가하면 될 것 같습니다.)
- `MainPage.tsx` 에 구글로그인 할 시 user의 displayName과 photoURL을 불러오도록 코드 수정했습니다.
🎁 PR Point
😭 어려웠던 점
- debounce가 어려웠습니다. 야무쌤께서 코드 이슈 해결해주시면 추후에 코드 수정해보겠습니다.

[feat] 마이페이지 debounce 함수 직접 제작 및 메인페이지 코드 수정

---

src/pages/MyPage/MyPage.tsx

#159 
✨ 구현 기능 명세
- 마이페이지 debounce 적용
- 페이지 새로고침 할 때 사용자 정보를 응답을 기다렸다가 페이지 렌더링 구현
🎁 PR Point
😭 어려웠던 점
- undefined(데이터 못불러오는 부분) -> 야무쌤 코드 참고해서 isLoading으로 구현

[feat] 마이페이지 debounce 적용 및 isLoading 상태 관리 추가

---

src/components/Footer/Footer.tsx

✨ 구현 기능 명세
[chore] 공지사항 목록 링크로 변경
🎁 PR Point
😭 어려웠던 점

[chore] 공지사항 목록 링크로 변경

---

src/components/SignUP/SignUp.tsx
src/pages/MyPage/MyPage.tsx

#180 #181 
✨ 구현 기능 명세
- 마이페이지 vaildation 추가했습니다.
- SignUp 컴포넌트에 회원가입 시 `phoneNumber`와 `address`에 기본 문구 설정하였습니다.
🎁 PR Point
😭 어려웠던 점
- 마이페이지 야무쌤 코드로 수정 후에 문제가 발생하여  `phoneNumber`와 `address`에 기본 문구를 강제로 설정한 느낌이라 실제 현업의 시각으로 보면 좋은 상황은 아닌 것 같습니다.

[feat] 마이페이지 vaildation 추가 및 SignUp 컴포넌트 수정

---

package.json

✨ 구현 기능 명세
- 베너이미지 변경
- script 수정
🎁 PR Point
.
😭 어려웠던 점
.

[chore] 베너이미지 변경

---

src/@types/global.d.ts
src/components/Button/ButtonKakao.tsx
src/pages/MyPage/MyPage.module.scss
src/pages/MyPage/MyPage.tsx

#31 #170 
✨ 구현 기능 명세
- 마이페이지 auth 정보가 없을 시 `사용자 정보 로딩 중...` 부분 SCSS 간단하게 적용했습니다.
- `ButtonKakao.tsx` 에 photoURL 경로 잘못 지정된 거 올바르게 설정했습니다. (하는 과정에서 `global.d.ts` 파일에 코드 한 줄 추가 했습니다.)
🎁 PR Point
😭 어려웠던 점

[chore] 마이페이지, 카카오 로그인 버튼 코드 리팩토링

---

src/components/Input/SearchForm.tsx
src/components/Modal/ModalPotal.tsx
src/components/Modal/ShowCard.tsx
src/components/Nav/Nav.tsx

#186 
✨ 구현 기능 명세
-build시 이미지 깨지는 문제 해결
🎁 PR Point
.
😭 어려웠던 점
.

[feat] 이미지 깨지는 문제 해결

---

package.json
src/@recoil/usersState.ts
src/components/Input/SearchForm.tsx
src/components/Modal/ReadMeetings.tsx
src/pages/MainPage/MainPage.tsx

✨ 구현 기능 명세
- 코드 리펙토링
🎁 PR Point
.
😭 어려웠던 점
.

[feat] 코드 리펙토링

---

src/components/Footer/Footer.module.scss
src/components/Footer/Footer.tsx

✨ 구현 기능 명세
[style] Footer에 Logo 위치 수정 및 불필요한 코드 삭제
🎁 PR Point
😭 어려웠던 점

[style] Footer에 Logo 위치 수정 및 불필요한 코드 삭제

---

index.html

✨ 구현 기능 명세
index.html 수정
🎁 PR Point
.
😭 어려웠던 점
.

[chore] index.html 수정

---

package-lock.json
package.json
src/@recoil/loadingState.ts
src/@recoil/searchTermState.ts
src/components/FoodList/FoodList.tsx
src/pages/Recommend/Recommend.module.scss
src/pages/Recommend/Recommend.tsx

#201 
✨ 구현 기능 명세
- 추천 :  검색필터링 구현 
(➡️ 전체 데이터에서가아니고 한 페이지안의 데이터에서만  적용이 되는 문제..)
- 페이지네이션 리펙토링
(➡️ react-paginate 설치하여 진행 )
🎁 PR Point
풀받고 npm i 해주세요!
😭 어려웠던 점
- 검색 필터링 구현

[feat] 추천 ,  검색필터링 구현

---

src/components/ChatDialog/Message/Message.tsx
src/context/AuthContext.tsx
src/pages/Recommend/Recommend.tsx

✨ 구현 기능 명세
로그인한 사용자마다 프로필 다르게 보이기
🎁 PR Point
.
😭 어려웠던 점
.

[feat]로그인한 사용자마다 프로필 다르게 보이기

---

src/components/Button/ButtonGoogle.tsx
src/components/ChatDialog/Message/Message.tsx
src/components/SignUP/SignUp.tsx

✨ 구현 기능 명세
- 구글 로그인시에도 채팅프로필에 설정한 이름과 이미지 표시
🎁 PR Point
.
😭 어려웠던 점
- 구글 로그인시에 파이어 스토어의 유저 컬렉션에 저장시켜 해결...!

[feat] 구글 로그인시에도 채팅프로필에 설정한 이름과 이미지 표시

---

src/pages/MyPage/MyPage.tsx

✨ 구현 기능 명세
- 구글 로그인시 마이페이지에 들어가면 로딩창이계속뜨는 이슈 해결
🎁 PR Point
.
😭 어려웠던 점
.

[feat] 구글 로그인시 마이페이지에 들어가면 로딩창이계속뜨는 이슈 해결

---

src/components/Button/ButtonKakao.tsx
src/components/ChatDialog/Message/Message.module.scss
src/components/ChatDialog/Message/Message.tsx
src/components/ChatDialog/Navbar/Navbar.module.scss
src/components/Input/SearchForm.tsx
src/pages/Chat/Chat.module.scss

✨ 구현 기능 명세
- kakao로그인시 채팅 프로필에 적용이 안되는 이슈 해결
🎁 PR Point
.
😭 어려웠던 점
.

[feat] kakao로그인시 채팅 프로필에 적용이 안되는 이슈 해결

---

src/components/ChatDialog/Message/Message.tsx
src/components/ChatDialog/Navbar/Navbar.tsx
src/pages/MyPage/MyPage.tsx
src/utils/signOut.tsx

✨ 구현 기능 명세
로그아웃 함수 재사용 함수로 분리
🎁 PR Point
.
😭 어려웠던 점
.

[chore] 로그아웃 함수 재사용 함수로 분리

---

package-lock.json
package.json
vite.config.ts

✨ 구현 기능 명세
이미지 최적화
🎁 PR Point
.
😭 어려웠던 점
.

[refactor] 이미지 최적화 구성

---

src/components/Button/Button.tsx
src/components/Button/ButtonGoogle.tsx
src/components/ChatDialog/Chattings/Chattings.tsx
src/components/ChatDialog/Navbar/Navbar.tsx
src/components/FoodList/FoodList.tsx
src/components/InputSelector/InputSelector.tsx
src/data/chatData.json
src/data/locationData.json
src/pages/MyPage/MyPage.tsx
src/pages/Recommend/Recommend.tsx
src/utils/signOut.ts

#222 #223
- signOut 재사용 함수로 분리후 적용
- 더미데이터를 json파일로 분리

[refactor] 코드 리펙토링

---

src/utils/signOut.ts

[chore] signOut 파일 type 추가
